services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-postgres
    environment:
      POSTGRES_USER: ukesh
      POSTGRES_PASSWORD: ukeshgurung
      POSTGRES_DB: ragdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build: ./services/auth-services
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    depends_on:
      - postgres
    ports:
      - "3001:3000"

  user-service:
    build: ./services/user-services
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    ports:
      - "3002:3000"

  api-gateway:
    build: ./services/APIGateway
    environment:
      JWT_SECRET: ${JWT_SECRET}
      USER_SERVICE_URL: http://user-service:3000
      AUTH_SERVICE_URL: http://auth-service:3000
    depends_on:
      - auth-service
      - user-service
    ports:
      - "8080:8080"

volumes:
  pgdata:
